apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-testcase-6
spec:
  destination:
    namespace: oci-testcase-6
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: subdirectory
    repoURL: 'oci://ghcr.io/sabre1041/argocd-oci-testcases/oci-manifests-nested'
    targetRevision: latest
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
