apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-testcase-12
spec:
  destination:
    namespace: oci-testcase-12
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: .
    repoURL: 'oci://<plain_http_registry>/<plain_http_repository>'
    targetRevision: latest
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
