apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-testcase-11
spec:
  destination:
    namespace: oci-testcase-11
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: .
    repoURL: 'oci://<untrusted_registry>/<untrusted_repository>'
    targetRevision: latest
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
